/* Generated By:JJTree: Do not edit this line. ASTClassDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=com.brandonflude.ldi.simplescript.interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.brandonflude.ldi.simplescript.parser.ast;

public
class ASTClassDef extends SimpleNode {
  public ASTClassDef(int id) {
    super(id);
  }

  public ASTClassDef(SimpleScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3d9f9dae287ecdd5c80926a86467e54f (do not edit this line) */
