/* Generated By:JJTree: Do not edit this line. ASTClassInvoke.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=com.brandonflude.ldi.simplescript.interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.brandonflude.ldi.simplescript.parser.ast;

public
class ASTClassInvoke extends SimpleNode {
  public ASTClassInvoke(int id) {
    super(id);
  }

  public ASTClassInvoke(SimpleScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e26ff0ddb188ecb818dc65fb3edb0bdb (do not edit this line) */
