/* Generated By:JJTree: Do not edit this line. ASTDecimal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=com.brandonflude.ldi.simplescript.interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.brandonflude.ldi.simplescript.parser.ast;

public
class ASTDecimal extends SimpleNode {
  public ASTDecimal(int id) {
    super(id);
  }

  public ASTDecimal(SimpleScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b1194d4ddeff07e49ff2fa48387d44fa (do not edit this line) */
